# get completions
"$schema" = 'https://starship.rs/config-schema.json'
#format = """
#[$directory]()[$character](bold)
#""" ╭ ╰
format = """
[┌──── \\[ ](cyan)\
$username\
[@]()\
$hostname\
[ \\] \\[ ](cyan)\
$directory\
[\\]](cyan)\
\n[└─ ](cyan)\
$character
"""

add_newline = true

[directory]
style = 'green'

[character]
# ❭
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[username]
format = '[$user](yellow)'
show_always = true

[hostname]
ssh_only = false
ssh_symbol = ""
trim_at = ""
disabled = false
style = "blue"
format = "[$hostname]($style)"

[package]
disabled = true
